# Generated by Django 2.1.5 on 2019-11-20 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ORC', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancework',
            name='maintenancework_closedate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
