# Generated by Django 2.1.5 on 2019-10-31 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ORC', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenancework',
            name='date',
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='date',
        ),
    ]
