# Generated by Django 2.1.5 on 2019-11-10 05:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ORC', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resident',
            fields=[
                ('resident_id', models.AutoField(auto_created=True, max_length=6, primary_key=True, serialize=False)),
                ('resident_name', models.CharField(max_length=50)),
                ('resident_occupation', models.CharField(max_length=50)),
                ('resident_emailaddress', models.CharField(max_length=50)),
                ('resident_marital_status', models.CharField(choices=[('--', '--'), ('Single', 'Single'), ('Married', 'Married')], default='--', max_length=50)),
                ('resident_familymember_count', models.IntegerField(verbose_name=10)),
                ('resident_petdetails', models.CharField(max_length=50)),
                ('resident_startdate', models.DateTimeField(auto_now_add=True)),
                ('resident_enddate', models.DateTimeField(auto_now_add=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='mwId',
        ),
        migrations.RemoveField(
            model_name='maintenancework',
            name='user',
        ),
        migrations.RemoveField(
            model_name='maintenancework',
            name='woId',
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='roomNumber',
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='user',
        ),
        migrations.DeleteModel(
            name='Equipment',
        ),
        migrations.DeleteModel(
            name='MaintenanceWork',
        ),
        migrations.DeleteModel(
            name='PropertyLocation',
        ),
        migrations.DeleteModel(
            name='Workorder',
        ),
    ]
