# Generated by Django 2.1.5 on 2019-10-26 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ORC', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='woPriority',
            field=models.CharField(choices=[('medium', 'Medium'), ('low', 'Low'), ('critical', 'Critical'), ('high', 'High')], default='low', max_length=10),
        ),
    ]
