# Generated by Django 2.1.5 on 2019-11-10 05:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ORC', '0002_auto_20191110_0523'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceWorker',
            fields=[
                ('worker_id', models.AutoField(auto_created=True, max_length=6, primary_key=True, serialize=False)),
                ('worker_name', models.CharField(max_length=50)),
                ('worker_emailaddress', models.CharField(max_length=50)),
                ('worker_address', models.CharField(max_length=50)),
                ('worker_yearsofexperience', models.IntegerField(verbose_name=10)),
                ('worker_contactdetails', models.CharField(max_length=10)),
                ('worker_startdate', models.DateTimeField(auto_now_add=True)),
                ('worker_enddate', models.DateTimeField(auto_now_add=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='resident',
            name='resident_contactdetails',
            field=models.CharField(default=4029969072, max_length=10),
            preserve_default=False,
        ),
    ]
