# Generated by Django 2.1.5 on 2019-11-19 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ORC', '0002_auto_20191118_2040'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orc_staff',
            old_name='orc_created_date',
            new_name='created_date',
        ),
        migrations.AlterField(
            model_name='maintenanceworker',
            name='worker_startdate',
            field=models.DateField(),
        ),
    ]
