# Generated by Django 2.1.5 on 2019-12-07 17:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ORC', '0002_auto_20191206_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='workorder_closedate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='workorder_duedate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='workorder_opendate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
