# Generated by Django 2.1.5 on 2019-10-31 03:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ORC', '0002_auto_20191031_0259'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
