# Generated by Django 2.1.5 on 2019-10-26 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ORC', '0002_auto_20191026_0353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='woPriority',
            field=models.CharField(choices=[('high', 'High'), ('low', 'Low'), ('critical', 'Critical'), ('medium', 'Medium')], default='low', max_length=10),
        ),
    ]
