# Generated by Django 2.1.5 on 2019-12-07 17:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ORC', '0003_auto_20191207_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenanceworker',
            name='worker_enddate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='maintenanceworker',
            name='worker_startdate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='resident',
            name='resident_enddate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='resident',
            name='resident_startdate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
