# Generated by Django 2.1.5 on 2019-10-26 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ORC', '0003_auto_20191026_0353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='woPriority',
            field=models.CharField(choices=[('low', 'Low'), ('critical', 'Critical'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=10),
        ),
    ]
