# Generated by Django 2.1.5 on 2019-11-10 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ORC', '0003_auto_20191110_0535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenanceworker',
            name='worker_yearsofexperience',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='resident',
            name='resident_familymember_count',
            field=models.IntegerField(max_length=10),
        ),
    ]
