# Generated by Django 2.1.5 on 2019-11-10 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ORC', '0004_auto_20191110_0537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenanceworker',
            name='worker_enddate',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='maintenanceworker',
            name='worker_startdate',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='resident',
            name='resident_enddate',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='resident',
            name='resident_startdate',
            field=models.DateTimeField(),
        ),
    ]
