# Generated by Django 2.1.5 on 2019-12-07 17:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ORC', '0005_auto_20191207_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancework',
            name='maintenancework_duedate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='maintenancework',
            name='maintenancework_opendate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='orc_staff',
            name='orc_staff_enddate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='orc_staff',
            name='orc_staff_startdate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
