# Generated by Django 2.1.5 on 2019-11-10 05:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ORC', '0005_auto_20191110_0538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenanceworker',
            name='created_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='maintenanceworker',
            name='worker_enddate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='resident',
            name='resident_enddate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='resident',
            name='resident_startdate',
            field=models.DateField(),
        ),
    ]
