# Generated by Django 2.1.5 on 2019-12-07 17:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ORC', '0006_auto_20191207_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancework',
            name='maintenancework_closedate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
