# Generated by Django 2.1.5 on 2019-11-10 06:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ORC', '0006_auto_20191110_0539'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('staff_id', models.AutoField(auto_created=True, max_length=6, primary_key=True, serialize=False)),
                ('staff_name', models.CharField(max_length=50)),
                ('staff_emailaddress', models.CharField(max_length=50)),
                ('staff_address', models.CharField(max_length=50)),
                ('staff_yearsofexperience', models.IntegerField(max_length=10)),
                ('staff_contactdetails', models.CharField(max_length=10)),
                ('staff_position', models.CharField(max_length=50)),
                ('staff_startdate', models.DateTimeField()),
                ('staff_enddate', models.DateField()),
                ('created_date', models.DateField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
