# Generated by Django 2.1.5 on 2019-11-10 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ORC', '0007_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenanceworker',
            name='worker_yearsofexperience',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='resident',
            name='resident_familymember_count',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='staff',
            name='staff_yearsofexperience',
            field=models.IntegerField(),
        ),
    ]
