# Generated by Django 2.1.5 on 2019-12-07 19:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ORC', '0007_auto_20191207_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancework',
            name='maintenancework_closedate',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
