# Generated by Django 2.1.5 on 2019-11-11 01:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ORC', '0008_auto_20191110_0007'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workorder',
            fields=[
                ('workorder_id', models.AutoField(auto_created=True, max_length=6, primary_key=True, serialize=False)),
                ('workorder_Description', models.CharField(max_length=50)),
                ('workorder_category', models.CharField(choices=[('--', '--'), ('Household Appliances', 'Household Appliances'), ('Furniture Repair', "Furniture Repair'"), ('Plumbling', 'Plumbling'), ('Pest Control', 'Pest Control'), ('Other Maintenance Work', 'Other Maintenance Work')], default='--', max_length=50)),
                ('workorder_priority', models.CharField(choices=[('--', '--'), ('Low', 'Low'), ('Moderate', 'Moderate'), ('High', 'High')], default='--', max_length=50)),
                ('workorder_opendate', models.DateTimeField()),
                ('workorder_duedate', models.DateTimeField()),
                ('workorder_closedate', models.DateTimeField()),
                ('is_open', models.BooleanField(default=True)),
                ('created_date', models.DateField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(auto_now_add=True)),
                ('resident_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='residents', to='ORC.Resident')),
                ('worker_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenanceworker', to='ORC.MaintenanceWorker')),
            ],
        ),
        migrations.AlterField(
            model_name='staff',
            name='staff_startdate',
            field=models.DateField(),
        ),
    ]
