# Generated by Django 2.1.5 on 2019-12-07 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ORC', '0009_auto_20191207_1324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenancework',
            name='residentname',
        ),
    ]
