# Generated by Django 2.1.5 on 2019-11-11 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ORC', '0009_auto_20191110_1949'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maintenanceworker',
            old_name='worker_name',
            new_name='maintenanceworker_name',
        ),
        migrations.RenameField(
            model_name='workorder',
            old_name='worker_name',
            new_name='maintenanceworker_name',
        ),
        migrations.AlterField(
            model_name='workorder',
            name='workorder_category',
            field=models.CharField(choices=[('--', '--'), ('Household Appliances', 'Household Appliances'), ('Furniture Repair', 'Furniture Repair'), ('Plumbling', 'Plumbling'), ('Pest Control', 'Pest Control'), ('Other Maintenance Work', 'Other Maintenance Work')], default='--', max_length=50),
        ),
    ]
