# Generated by Django 2.1.5 on 2019-11-11 02:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ORC', '0010_auto_20191110_1952'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyLocation',
            fields=[
                ('property_id', models.AutoField(auto_created=True, max_length=6, primary_key=True, serialize=False)),
                ('property_number', models.IntegerField(max_length=10)),
                ('property_building', models.CharField(choices=[('--', '--'), ('Atlas', 'Atlas'), ('Brook', 'Brook'), ('Aon', 'Aon'), ('Elite', 'Elite')], default='--', max_length=50)),
                ('is_available', models.BooleanField(default=True)),
                ('created_date', models.DateField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
