# Generated by Django 2.1.5 on 2019-11-11 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ORC', '0011_propertylocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertylocation',
            name='property_number',
            field=models.IntegerField(),
        ),
    ]
