# Generated by Django 2.1.5 on 2019-11-11 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ORC', '0012_auto_20191110_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertylocation',
            name='property_floor',
            field=models.CharField(choices=[('--', '--'), ('Lower Ground', 'Lower Groun'), ('Ground', 'Ground'), ('First', 'First'), ('Second', 'Second')], default='--', max_length=50),
        ),
    ]
