# Generated by Django 2.1.5 on 2019-11-11 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ORC', '0013_propertylocation_property_floor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertylocation',
            name='property_floor',
            field=models.CharField(choices=[('--', '--'), ('Lower Ground', 'Lower Ground'), ('Ground', 'Ground'), ('First', 'First'), ('Second', 'Second')], default='--', max_length=50),
        ),
    ]
