# Generated by Django 2.1.5 on 2019-12-14 23:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ORC', '0014_auto_20191214_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomallotment',
            name='allotment_enddate',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 14, 23, 58, 29, 179624, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='roomallotment',
            name='allotment_startdate',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 14, 23, 58, 29, 179624, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='workorder_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
