# Generated by Django 2.1.5 on 2019-11-11 02:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ORC', '0014_auto_20191110_2024'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('equipment_id', models.AutoField(auto_created=True, max_length=6, primary_key=True, serialize=False)),
                ('equipment_serialnumber', models.IntegerField()),
                ('equipment_name', models.CharField(max_length=10)),
                ('equipment_description', models.CharField(max_length=50)),
                ('is_available', models.BooleanField(default=True)),
                ('equipment_cost', models.IntegerField()),
                ('equipment_purchasedate', models.DateField()),
                ('created_date', models.DateField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='maintenanceworker_name',
        ),
    ]
