# Generated by Django 2.1.5 on 2019-11-11 03:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ORC', '0015_auto_20191110_2040'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceWork',
            fields=[
                ('maintenancework_id', models.AutoField(auto_created=True, max_length=6, primary_key=True, serialize=False)),
                ('maintenacework_title', models.CharField(max_length=20)),
                ('maintenancework_description', models.CharField(max_length=50)),
                ('maintenancework_cost', models.IntegerField()),
                ('maintenancework_opendate', models.DateTimeField()),
                ('maintenancework_duedate', models.DateTimeField()),
                ('is_open', models.BooleanField(default=True)),
                ('maintenanceworkr_closedate', models.DateTimeField()),
                ('created_date', models.DateField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(auto_now_add=True)),
                ('equipment_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mw4', to='ORC.Equipment')),
                ('maintenanceworker_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mw2', to='ORC.MaintenanceWorker')),
                ('property_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mw3', to='ORC.PropertyLocation')),
                ('workorder_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mw1', to='ORC.Workorder')),
            ],
        ),
    ]
