# Generated by Django 2.1.5 on 2019-11-11 03:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ORC', '0016_maintenancework'),
    ]

    operations = [
        migrations.CreateModel(
            name='Roomallotment',
            fields=[
                ('allotment_id', models.AutoField(auto_created=True, max_length=6, primary_key=True, serialize=False)),
                ('allotment_startdate', models.DateTimeField()),
                ('allotment_enddate', models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='propertylocation',
            name='property_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AddField(
            model_name='roomallotment',
            name='property_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mww1', to='ORC.PropertyLocation'),
        ),
        migrations.AddField(
            model_name='roomallotment',
            name='resident_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='residents1', to='ORC.Resident'),
        ),
    ]
