# Generated by Django 2.1.5 on 2019-11-11 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ORC', '0017_auto_20191110_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='equipment_serialnumber',
            field=models.CharField(max_length=10),
        ),
    ]
