# Generated by Django 2.1.5 on 2019-11-11 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ORC', '0018_auto_20191110_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancework',
            name='maintenacework_title',
            field=models.CharField(max_length=30),
        ),
    ]
