# Generated by Django 2.1.5 on 2019-11-11 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ORC', '0020_auto_20191110_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='workorder_closedate',
            field=models.DateTimeField(),
        ),
    ]
