# Generated by Django 2.1.5 on 2019-11-11 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ORC', '0021_auto_20191110_2129'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maintenancework',
            old_name='workorder_id',
            new_name='workorder_description',
        ),
    ]
