# Generated by Django 2.1.5 on 2019-11-11 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ORC', '0022_auto_20191110_2132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenancework',
            name='maintenacework_title',
        ),
    ]
