# Generated by Django 2.1.5 on 2019-11-11 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ORC', '0023_remove_maintenancework_maintenacework_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maintenancework',
            old_name='workorder_description',
            new_name='workorder_id',
        ),
        migrations.AlterField(
            model_name='workorder',
            name='workorder_id',
            field=models.CharField(auto_created=True, max_length=6, primary_key=True, serialize=False),
        ),
    ]
