# Generated by Django 2.1.5 on 2019-11-11 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ORC', '0024_auto_20191110_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='workorder_id',
            field=models.CharField(auto_created=True, max_length=20, primary_key=True, serialize=False),
        ),
    ]
