# Generated by Django 2.1.5 on 2019-11-12 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ORC', '0025_auto_20191110_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancework',
            name='property_building',
            field=models.ForeignKey(default=101, on_delete=django.db.models.deletion.CASCADE, related_name='mww5', to='ORC.PropertyLocation'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roomallotment',
            name='property_building',
            field=models.ForeignKey(default=101, on_delete=django.db.models.deletion.CASCADE, related_name='mww2', to='ORC.PropertyLocation'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='propertylocation',
            name='property_number',
            field=models.CharField(choices=[('--', '--'), (' 101', '101'), ('102', '102'), ('103', '103'), ('104', '104'), ('201', '201'), ('202', '202'), ('203', '203'), ('204', '204'), ('301', '301'), ('302', '302'), ('303', '303'), ('304', '304'), ('401', '401'), ('402', '402'), ('403', '403'), ('404', '404')], default='--', max_length=50),
        ),
    ]
