# Generated by Django 2.1.5 on 2019-11-12 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ORC', '0027_auto_20191112_1338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenancework',
            name='property_building',
        ),
        migrations.RemoveField(
            model_name='maintenancework',
            name='property_number',
        ),
        migrations.RemoveField(
            model_name='roomallotment',
            name='property_building',
        ),
        migrations.AddField(
            model_name='roomallotment',
            name='property_floor',
            field=models.CharField(choices=[('--', '--'), ('Lower Ground', 'Lower Ground'), ('Ground', 'Ground'), ('First', 'First'), ('Second', 'Second')], default='--', max_length=50),
        ),
        migrations.AlterField(
            model_name='roomallotment',
            name='property_number',
            field=models.CharField(choices=[('--', '--'), (' 101', 'Atlas101'), ('102', 'Atlas102'), ('103', 'Atlas103'), ('104', 'Atlas104'), ('201', 'Atlas201'), ('202', 'Atlas202'), ('203', 'Atlas203'), ('204', 'Atlas204'), ('301', 'Atlas301'), ('302', 'Atlas302'), ('303', 'Atlas303'), ('304', 'Atlas304'), ('401', 'Atlas401'), ('402', 'Atlas402'), ('403', 'Atlas403'), ('404', 'Atlas404'), ('101', 'Brook101'), ('102', 'Brook102'), ('103', 'Brook103'), ('104', 'Brook104'), ('201', 'Brook201'), ('202', 'Brook202'), ('203', 'Brook203'), ('204', 'Brook204'), ('301', 'Brook301'), ('302', 'Brook302'), ('303', 'Brook303'), ('304', 'Brook304'), ('401', 'Brook401'), ('402', 'Brook402'), ('403', 'Brook403'), ('404', 'Brook404'), ('101', 'AON101'), ('102', 'AON102'), ('103', 'AON103'), ('104', 'AON104'), ('201', 'AON201'), ('202', 'AON202'), ('203', 'AON203'), ('204', 'AON204'), ('301', 'AON301'), ('302', 'AON302'), ('303', 'AON303'), ('304', 'AON304'), ('401', 'AON401'), ('402', 'AON402'), ('403', 'AON403'), ('404', 'AON404')], default='--', max_length=50),
        ),
        migrations.DeleteModel(
            name='PropertyLocation',
        ),
    ]
