# Generated by Django 2.1.5 on 2019-11-12 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ORC', '0028_auto_20191112_1347'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maintenancework',
            old_name='maintenanceworkr_closedate',
            new_name='maintenancework_closedate',
        ),
        migrations.AddField(
            model_name='maintenancework',
            name='property_number',
            field=models.ForeignKey(default=0.0004952947003467063, on_delete=django.db.models.deletion.CASCADE, related_name='mw3', to='ORC.Roomallotment'),
            preserve_default=False,
        ),
    ]
