# Generated by Django 2.1.5 on 2019-11-12 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ORC', '0029_auto_20191112_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomallotment',
            name='property_number',
            field=models.CharField(choices=[('--', '--'), ('Atlas101', 'Atlas101'), ('Atlas102', 'Atlas102'), ('Atlas103', 'Atlas103'), ('Atlas104', 'Atlas104'), ('Atlas201', 'Atlas201'), ('Atlas202', 'Atlas202'), ('Atlas203', 'Atlas203'), ('Atlas204', 'Atlas204'), ('Atlas301', 'Atlas301'), ('Atlas302', 'Atlas302'), ('Atlas303', 'Atlas303'), ('Atlas304', 'Atlas304'), ('Atlas401', 'Atlas401'), ('Atlas402', 'Atlas402'), ('Atlas403', 'Atlas403'), ('Atlas404', 'Atlas404'), ('Brook101', 'Brook101'), ('Brook102', 'Brook102'), ('Brook103', 'Brook103'), ('Brook104', 'Brook104'), ('Brook201', 'Brook201'), ('Brook202', 'Brook202'), ('Brook203', 'Brook203'), ('Brook204', 'Brook204'), ('Brook301', 'Brook301'), ('Brook302', 'Brook302'), ('Brook303', 'Brook303'), ('Brook304', 'Brook304'), ('Brook401', 'Brook401'), ('Brook402', 'Brook402'), ('Brook403', 'Brook403'), ('Brook404', 'Brook404'), ('AON101', 'AON101'), ('AON102', 'AON102'), ('AON103', 'AON103'), ('AON104', 'AON104'), ('AON201', 'AON201'), ('AON202', 'AON202'), ('AON203', 'AON203'), ('AON204', 'AON204'), ('AON301', 'AON301'), ('AON302', 'AON302'), ('AON303', 'AON303'), ('AON304', 'AON304'), ('AON401', 'AON401'), ('AON402', 'AON402'), ('AON403', 'AON403'), ('AON404', 'AON404')], default='--', max_length=50),
        ),
    ]
