# Generated by Django 2.1.5 on 2019-11-12 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ORC', '0030_auto_20191112_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='equipment_name',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
