# Generated by Django 2.1.5 on 2019-11-12 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ORC', '0032_auto_20191112_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='property_number',
            field=models.ForeignKey(default=101, on_delete=django.db.models.deletion.CASCADE, related_name='wo1', to='ORC.Roomallotment'),
            preserve_default=False,
        ),
    ]
